apiVersion: batch/v1
kind: CronJob
metadata:
  name: cpu-utilization-job
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cpu-utilization
            image: akanksh05/cronjob:cron.v2 # Use your built image
            command: ["python", "/scripts/fetch_cpu_utilization.py"]
            volumeMounts:
            - name: cpu-logs
              mountPath: /path/to
          restartPolicy: OnFailure
          volumes:
          - name: cpu-logs
            hostPath:
              path: "/path/to"  # Ensure this is a string